var needsTagsStr = "<b>Not fully tagged</b>",
noDataStr = "",
themeStr = "<b>Theme</b>: ",
boardGames = [
	{
		"name": "4 Player Chess",
		"version": "",
		"url": "https://boardgamegeek.com/boardgame/2173/4-player-chess",
		"category": "Board Game",
		"gameplayType": "Competitive",
		"tags": ["board", "last one standing", "no randomness", "player elimination"],
		"minPlayers": 2,
		"maxPlayers": 4,
		"numPlayersNote": [
			"",
			""
		],
		"minTime": 45,
		"maxTime": 45,
		"complexity": 2.89,
		"lastPlayed": noDataStr,
		"storageLocation": "Home",
		"description": "Chess pieces on each edge, with adjusted movement, capture, and victory rules",
		"notes": "",
		"wip": false,
		"expansions": []
	},
	{
		"name": "Aberration",
		"version": "",
		"url": "https://boardgamegeek.com/boardgame/395834/aberration",
		"category": "Board Game",
		"gameplayType": "Cooperative",
		"tags": [needsTagsStr, "area defense", "board", "cards", "dice", themeStr + "supernatural horror", "worker placement"],
		"minPlayers": 1,
		"maxPlayers": 4,
		"numPlayersNote": [
			"",
			""
		],
		"minTime": 60,
		"maxTime": 90,
		"complexity": 2.6,
		"lastPlayed": noDataStr,
		"storageLocation": noDataStr,
		"description": "Tower defense game where players pick a character and class with different powers to protect a village from nightly attacks, upgrading and fortifying along the way",
		"notes": "",
		"wip": true,
		"expansions": [
			{
				"name": "Arcanists & Abominations",
				"version": "Expansion",
				"url": "https://boardgamegeek.com/boardgameexpansion/476472/aberration-arcanists-and-abominations",
				"category": "Board Game",
				"gameplayType": "Cooperative",
				"tags": [needsTagsStr, "area defense", "board", "cards", "dice", themeStr + "supernatural horror", "worker placement"],
				"minPlayers": 1,
				"maxPlayers": 4,
				"numPlayersNote": [
					"",
					""
				],
				"minTime": 60,
				"maxTime": 90,
				"complexity": 0,
				"lastPlayed": noDataStr,
				"storageLocation": noDataStr,
				"description": "Adds new classes and monsters",
				"notes": "",
				"wip": true
			},
			{
				"name": "Oblivion's Embrace",
				"version": "Expansion",
				"url": "https://boardgamegeek.com/boardgameexpansion/476392/aberration-oblivions-embrace",
				"category": "Board Game",
				"gameplayType": "Cooperative",
				"tags": [needsTagsStr, "area defense", "board", "cards", "dice", "narrative", "roguelike", themeStr + "supernatural horror", "worker placement"],
				"minPlayers": 1,
				"maxPlayers": 4,
				"numPlayersNote": [
					"",
					""
				],
				"minTime": 60,
				"maxTime": 90,
				"complexity": 0,
				"lastPlayed": noDataStr,
				"storageLocation": noDataStr,
				"description": "Adds two narrative campaigns consisting of multiple missions, about defending the village from a cult",
				"notes": "",
				"wip": true
			}
		]
	},
	{
		"name": "Almighty: The Godliest God Game",
		"version": "",
		"url": "https://boardgamegeek.com/boardgame/382158/almighty",
		"category": "Board Game",
		"gameplayType": "Competitive",
		"tags": [needsTagsStr, "board", themeStr + "competing deities"],
		"minPlayers": 1,
		"maxPlayers": 4,
		"numPlayersNote": [
			"",
			""
		],
		"minTime": 60,
		"maxTime": 90,
		"complexity": 2.5,
		"lastPlayed": noDataStr,
		"storageLocation": noDataStr,
		"description": "Each player is a different nature god, competing for glory from mortals by affecting their lives in different ways",
		"notes": "",
		"wip": true,
		"expansions": []
	},
	{
		"name": "Anachrony",
		"version": "",
		"url": "https://boardgamegeek.com/boardgame/185343/anachrony",
		"category": "Board Game",
		"gameplayType": "Competitive",
		"tags": ["board", "dice", themeStr + "post-apocalypse", themeStr + "time travel", "worker placement"],
		"minPlayers": 1,
		"maxPlayers": 4,
		"numPlayersNote": [
			"",
			""
		],
		"minTime": 30,
		"maxTime": 120,
		"complexity": 4,
		"lastPlayed": noDataStr,
		"storageLocation": "Home",
		"description": "Post-apocalypse, four different factions trying to use time travel in different ways to avert a future disaster and rule Earth",
		"notes": "",
		"wip": false,
		"expansions": []
	},
	{
		"name": "Arkham Horror",
		"version": "1st Edition",
		"url": "https://boardgamegeek.com/boardgame/15987/arkham-horror",
		"category": "Board Game",
		"gameplayType": "Cooperative",
		"tags": ["board", "cards", "dice", themeStr + "supernatural horror"],
		"minPlayers": 1,
		"maxPlayers": 8,
		"numPlayersNote": [
			"Solo mode's rules are different",
			""
		],
		"minTime": 120,
		"maxTime": 240,
		"complexity": 3.59,
		"lastPlayed": "2010's",
		"storageLocation": "Home",
		"description": "A Great Old One is awakening in Arkham and your party has to figure out how to stop them before they wake up and destroy everything",
		"notes": "Old game, the board's folds aren't all intact anymore",
		"wip": false,
		"expansions": []
	},
	{
		"name": "Ascendancy",
		"version": "",
		"url": "https://boardgamegeek.com/boardgame/258295/ascendancy",
		"category": "Board Game",
		"gameplayType": "Competitive",
		"tags": [needsTagsStr, "board", "cards", themeStr + "competing for the crown"],
		"minPlayers": 2,
		"maxPlayers": 4,
		"numPlayersNote": [
			"",
			""
		],
		"minTime": 90,
		"maxTime": 480,
		"complexity": 3.86,
		"lastPlayed": noDataStr,
		"storageLocation": noDataStr,
		"description": "Everyone is a different noble house competing for the crown across multiple generations, trying to build the greatest empire",
		"notes": "",
		"wip": true,
		"expansions": []
	},
	{
		"name": "Betrayal at House on the Hill",
		"version": "2nd Edition",
		"url": "https://boardgamegeek.com/boardgame/10547/betrayal-at-house-on-the-hill",
		"category": "Board Game",
		"gameplayType": "Team-Competitive",
		"tags": ["asymmetric gameplay/victory", "cards", "dice", "hidden information", "player elimination", themeStr + "supernatural horror", "tile placement", "traitor(s)"],
		"minPlayers": 3,
		"maxPlayers": 6,
		"numPlayersNote": [
			"",
			""
		],
		"minTime": 60,
		"maxTime": 120,
		"complexity": 2.4,
		"lastPlayed": "2020's",
		"storageLocation": "Home",
		"description": "Everyone explores a procedurally-generated haunted house until a random \"haunt\" event occurs that turns one player against the rest",
		"notes": "Box has a hole and has been bleached by sitting in the sun. Contents are fine though",
		"wip": false,
		"expansions": [
			{
				"name": "Widow's Walk",
				"version": "Expansion",
				"url": "https://boardgamegeek.com/boardgameexpansion/198452/betrayal-at-house-on-the-hill-widows-walk",
				"category": "Board Game",
				"gameplayType": "Team-Competitive",
				"tags": ["asymmetric gameplay/victory", "cards", "dice", "hidden information", "player elimination", themeStr + "supernatural horror", "tile placement", "traitor(s)"],
				"minPlayers": 3,
				"maxPlayers": 6,
				"numPlayersNote": [
					"",
					""
				],
				"minTime": 60,
				"maxTime": 120,
				"complexity": 2.78,
				"lastPlayed": noDataStr,
				"storageLocation": "Home",
				"description": "Adds more haunts and a 4th, rooftop floor to the base game",
				"notes": "",
				"wip": false
			}
		]
	},
	{
		"name": "Betrayal at House on the Hill",
		"version": "3rd Edition",
		"url": "https://boardgamegeek.com/boardgame/358504/betrayal-at-house-on-the-hill-3rd-edition",
		"category": "Board Game",
		"gameplayType": "Team-Competitive",
		"tags": ["asymmetric gameplay/victory", "cards", "dice", "hidden information", "player elimination", themeStr + "supernatural horror", "tile placement", "traitor(s)"],
		"minPlayers": 3,
		"maxPlayers": 6,
		"numPlayersNote": [
			"",
			""
		],
		"minTime": 60,
		"maxTime": 120,
		"complexity": 2.42,
		"lastPlayed": "2026",
		"storageLocation": "Home",
		"description": "Everyone explores a procedurally-generated haunted house until a random \"haunt\" event occurs that turns one player against the rest",
		"notes": "Possible haunts are restricted before the game starts, by having the group choose the reason why they're in the house to begin with. Easier for new players, but more predictable for experienced ones",
		"wip": false,
		"expansions": []
	},
	{
		"name": "Blasphemous: The Board Game",
		"version": "",
		"url": "https://boardgamegeek.com/boardgame/425745/blasphemous-the-board-game",
		"category": "Board Game",
		"gameplayType": "Competitive",
		"tags": [needsTagsStr, "board", "dice", themeStr + "post-apocalypse"],
		"minPlayers": 1,
		"maxPlayers": 4,
		"numPlayersNote": [
			"",
			""
		],
		"minTime": 90,
		"maxTime": 120,
		"complexity": 3.63,
		"lastPlayed": noDataStr,
		"storageLocation": noDataStr,
		"description": "Everyone is a Penitent trying to do quests (some require cooperation) and complete a Pilgrimage to earn redemption",
		"notes": "Based on Blasphemous, a very fun Metroidvania game with a great vibe and story",
		"wip": true,
		"expansions": []
	},
	{
		"name": "Bomb Busters",
		"version": "",
		"url": "https://boardgamegeek.com/boardgame/413246/bomb-busters",
		"category": "Board Game",
		"gameplayType": "Cooperative",
		"tags": ["board", "cards", "hidden information"],
		"minPlayers": 2,
		"maxPlayers": 5,
		"numPlayersNote": [
			"",
			""
		],
		"minTime": 30,
		"maxTime": 30,
		"complexity": 1.98,
		"lastPlayed": "2026",
		"storageLocation": "Home",
		"description": "Players cooperate to defuse a bomb by matching one of their wires to another player's wire; can play different scenarios, with different initial conditions based on cards drawn",
		"notes": "",
		"wip": false,
		"expansions": []
	},
	{
		"name": "Carcassonne",
		"version": "",
		"url": "https://boardgamegeek.com/boardgame/822/carcassonne",
		"category": "Board Game",
		"gameplayType": "Competitive",
		"tags": [themeStr + "city building", "tile placement", "worker placement"],
		"minPlayers": 2,
		"maxPlayers": 5,
		"numPlayersNote": [
			"",
			""
		],
		"minTime": 30,
		"maxTime": 45,
		"complexity": 1.88,
		"lastPlayed": "2026",
		"storageLocation": "Car",
		"description": "Players place terrain tiles that match up with existing geography, then claim those geographic features for points by placing workers",
		"notes": "",
		"wip": false,
		"expansions": []
	},
	{
		"name": "Coup",
		"version": "",
		"url": "https://boardgamegeek.com/boardgame/131357/coup",
		"category": "Card Game",
		"gameplayType": "Competitive",
		"tags": ["cards", "hidden information", "last one standing", "player elimination"],
		"minPlayers": 2,
		"maxPlayers": 6,
		"numPlayersNote": [
			"",
			""
		],
		"minTime": 15,
		"maxTime": 15,
		"complexity": 1.41,
		"lastPlayed": "2026",
		"storageLocation": "Car",
		"description": "Players have hidden roles with different powers, and they can lie about which roles they have unless someone calls them out; last one standing wins",
		"notes": "",
		"wip": false,
		"expansions": []
	},
	{
		"name": "Curses & Covens",
		"version": "",
		"url": "https://boardgamegeek.com/boardgame/370837/curses-and-covens",
		"category": "Card Game",
		"gameplayType": "Team-Competitive",
		"tags": ["asymmetric gameplay/victory", needsTagsStr, "cards", "hidden information", "traitor(s)"],
		"minPlayers": 4,
		"maxPlayers": 6,
		"numPlayersNote": [
			"",
			""
		],
		"minTime": 10,
		"maxTime": 20,
		"complexity": 2,
		"lastPlayed": noDataStr,
		"storageLocation": "Car",
		"description": "One player is the witch hunter while everyone else is a villager trying to hide the town's witches from the hunter",
		"notes": "",
		"wip": false,
		"expansions": []
	},
	{
		"name": "Dead Cells: The Rogue-Lite Board Game",
		"version": "Collector's Edition",
		"url": "https://boardgamegeek.com/boardgame/380135/dead-cells-the-rogue-lite-board-game",
		"category": "Board Game",
		"gameplayType": "Cooperative",
		"tags": ["board", "cards", "dice", "roguelike"],
		"minPlayers": 1,
		"maxPlayers": 4,
		"numPlayersNote": [
			"",
			"3 is the ideal number of players, 4 players don't quite fit into the combat system"
		],
		"minTime": 45,
		"maxTime": 45,
		"complexity": 2.39,
		"lastPlayed": noDataStr,
		"storageLocation": "Home",
		"description": "Your party is trying to survive different biomes and fight different bosses until you reach the end; death sends you back to the beginning, retaining the unlocks you earned in the last run",
		"notes": "Based on the roguelite Dead Cells, one of my favorite games",
		"wip": false,
		"expansions": []
	},
	{
		"name": "Dead by Daylight: The Board Game",
		"version": "Collector's Edition",
		"url": "https://boardgamegeek.com/boardgame/369103/dead-by-daylight-the-board-game-collectors-edition",
		"category": "Board Game",
		"gameplayType": "Team-Competitive",
		"tags": ["asymmetric gameplay/victory", "board", "dice", "player elimination", themeStr + "supernatural horror"],
		"minPlayers": 3,
		"maxPlayers": 5,
		"numPlayersNote": [
			"",
			"Balanced around a full team of 4 Survivors and 1 Killer"
		],
		"minTime": 30,
		"maxTime": 60,
		"complexity": 2.83,
		"lastPlayed": noDataStr,
		"storageLocation": "Home",
		"description": "One player is the Killer, and is trying to hunt and sacrifice everyone else, who play the Survivors trying to escape",
		"notes": "Based on the asymmetric multiplayer game Dead by Daylight. Collector's Edition comes with more content, plus plastic figures instead of tokens for killers and hooks",
		"wip": false,
		"expansions": []
	},
	{
		"name": "Devil's Dice",
		"version": "",
		"url": "https://boardgamegeek.com/boardgame/400796/devils-dice",
		"category": "Board Game",
		"gameplayType": "Competitive",
		"tags": ["board", "dice", "hidden information", themeStr + "demons"],
		"minPlayers": 2,
		"maxPlayers": 6,
		"numPlayersNote": [
			"",
			""
		],
		"minTime": 10,
		"maxTime": 20,
		"complexity": 2,
		"lastPlayed": "2026",
		"storageLocation": "Car",
		"description": "Players roll hidden dice with special symbols that let you collect money, steal dice, and ultimately get a full set of each symbol; can bluff and call other players' bluffs, like Coup",
		"notes": "",
		"wip": false,
		"expansions": [
			{
				"name": "Advanced Summoning",
				"version": "Expansion",
				"url": "https://boardgamegeek.com/boardgameexpansion/452198/devils-dice-advanced-summoning",
				"category": "Board Game",
				"gameplayType": "Competitive",
				"tags": ["board", "dice", "hidden information", themeStr + "demons"],
				"minPlayers": 2,
				"maxPlayers": 6,
				"numPlayersNote": [
					"",
					""
				],
				"minTime": 15,
				"maxTime": 20,
				"complexity": 2,
				"lastPlayed": "2026",
				"storageLocation": "Car",
				"description": "Special actions can be taken by claiming combinations of symbols",
				"notes": "",
				"wip": false
			}
		]
	},
	{
		"name": "Die in the Dungeon: The Board Game",
		"version": "Deluxe Edition",
		"url": "https://boardgamegeek.com/boardgame/462623/die-in-the-dungeon-the-board-game",
		"category": "Board Game",
		"gameplayType": "Cooperative",
		"tags": [needsTagsStr, "board", "dice", "roguelike"],
		"minPlayers": 1,
		"maxPlayers": 4,
		"numPlayersNote": [
			"",
			""
		],
		"minTime": 45,
		"maxTime": 90,
		"complexity": 0,
		"lastPlayed": noDataStr,
		"storageLocation": noDataStr,
		"description": "Dice-building roguelike game in which you play a squad of heroes diving into a dungeon to overcome challenges and get rewards",
		"notes": "Based on the roguelike game Die in the Dungeon",
		"wip": true,
		"expansions": []
	},
	{
		"name": "Drillers",
		"version": "",
		"url": "https://boardgamegeek.com/boardgame/465669/drillers",
		"category": "Board Game",
		"gameplayType": "Competitive",
		"tags": ["board", "cards", themeStr + "digging for resources"],
		"minPlayers": 1,
		"maxPlayers": 4,
		"numPlayersNote": [
			"",
			""
		],
		"minTime": 30,
		"maxTime": 120,
		"complexity": 2.64,
		"lastPlayed": "2026",
		"storageLocation": "Home",
		"description": "Players in drill mechs with limited resources compete to dig tunnels and collect minerals, then return to the surface to sell the minerals and upgrade their mech with better gear",
		"notes": "",
		"wip": false,
		"expansions": []
	},
	{
		"name": "Feed the Kraken",
		"version": "",
		"url": "https://boardgamegeek.com/boardgame/271601/feed-the-kraken",
		"category": "Board Game",
		"gameplayType": "Team-Competitive",
		"tags": ["board", "cards", "hidden information", "player elimination", "traitor(s)", themeStr + "pirates"],
		"minPlayers": 5,
		"maxPlayers": 11,
		"numPlayersNote": [
			"",
			""
		],
		"minTime": 45,
		"maxTime": 90,
		"complexity": 2.18,
		"lastPlayed": "2026",
		"storageLocation": "Home",
		"description": "Social deduction game with crewmates, pirates, and one cultist trying to steer the ship toward their preferred destination",
		"notes": "",
		"wip": false,
		"expansions": []
	},
	{
		"name": "Fire Tower",
		"version": "",
		"url": "https://boardgamegeek.com/boardgame/226605/fire-tower",
		"category": "Board Game",
		"gameplayType": "Competitive",
		"tags": ["board", "cards", "dice", "last one standing", "player elimination"],
		"minPlayers": 2,
		"maxPlayers": 4,
		"numPlayersNote": [
			"",
			""
		],
		"minTime": 15,
		"maxTime": 30,
		"complexity": 1.75,
		"lastPlayed": "2026",
		"storageLocation": "Home",
		"description": "Everyone is in their own fire tower in a burning forest, and they're fighting to be the last tower standing by putting out fires near them and starting fires near their opponents",
		"notes": "",
		"wip": false,
		"expansions": [
			{
				"name": "Rising Flames",
				"version": "Expansion",
				"url": "https://boardgamegeek.com/boardgameexpansion/311033/fire-tower-rising-flames",
				"category": "Board Game",
				"gameplayType": "Competitive",
				"tags": ["board", "cards", "dice", "last one standing", "player elimination"],
				"minPlayers": 1,
				"maxPlayers": 5,
				"numPlayersNote": [
					"Expansion adds a solo mode",
					"Expansion adds a role for a 5th player"
				],
				"minTime": 15,
				"maxTime": 30,
				"complexity": 2.67,
				"lastPlayed": "2025",
				"storageLocation": "Home",
				"description": "New mechanics are added to the base game, such as adding new \"firehawk\" defenses that can remove flames from your area and drop them in opponents' areas",
				"notes": "",
				"wip": false
			}
		]
	},
	{
		"name": "Five Crowns",
		"version": "",
		"url": "https://boardgamegeek.com/boardgame/1472/five-crowns",
		"category": "Card Game",
		"gameplayType": "Competitive",
		"tags": ["cards"],
		"minPlayers": 1,
		"maxPlayers": 7,
		"numPlayersNote": [
			"",
			""
		],
		"minTime": 30,
		"maxTime": 30,
		"complexity": 1.22,
		"lastPlayed": "2026",
		"storageLocation": "Car",
		"description": "Like Rummy, go for 3-of-a-kind or better, or suited straights, and get rid of all your cards",
		"notes": "",
		"wip": false,
		"expansions": []
	},
	{
		"name": "For the Gods!",
		"version": "",
		"url": "https://boardgamegeek.com/boardgame/444234/for-the-gods",
		"category": "Board Game",
		"gameplayType": "Competitive",
		"tags": [needsTagsStr, "board", themeStr + "competing deities"],
		"minPlayers": 2,
		"maxPlayers": 4,
		"numPlayersNote": [
			"",
			""
		],
		"minTime": 30,
		"maxTime": 60,
		"complexity": 2.25,
		"lastPlayed": noDataStr,
		"storageLocation": noDataStr,
		"description": "Each player is a different Greek god, competing to establish and control temples to dominate different areas",
		"notes": "",
		"wip": true,
		"expansions": []
	},
	{
		"name": "Fortune & Famine",
		"version": "",
		"url": "https://boardgamegeek.com/boardgame/329017/fortune-and-famine",
		"category": "Board Game",
		"gameplayType": "Competitive",
		"tags": [needsTagsStr, "board", "cards"],
		"minPlayers": 2,
		"maxPlayers": 6,
		"numPlayersNote": [
			"",
			""
		],
		"minTime": 30,
		"maxTime": 90,
		"complexity": 2,
		"lastPlayed": "2026",
		"storageLocation": "Home",
		"description": "Each player is a monarch of a kingdom, trying to recruit workers to earn money and grow the most wheat",
		"notes": "",
		"wip": false,
		"expansions": [
			{
				"name": "",
				"version": "Expansion",
				"url": "https://boardgamegeek.com/boardgame/412440/fortune-and-famine-expansion",
				"category": "Board Game",
				"gameplayType": "Competitive",
				"tags": [needsTagsStr, "board", "cards"],
				"minPlayers": 2,
				"maxPlayers": 6,
				"numPlayersNote": [
					"",
					""
				],
				"minTime": 30,
				"maxTime": 90,
				"complexity": 2,
				"lastPlayed": "2026",
				"storageLocation": "Home",
				"description": "Adds a structure-making mechanic to the base game",
				"notes": "",
				"wip": false
			}
		]
	},
	{
		"name": "Fury of Dracula",
		"version": "5th Edition",
		"url": "https://boardgamegeek.com/boardgame/469328/fury-of-dracula-fifth-edition",
		"category": "Board Game",
		"gameplayType": "Team-Competitive",
		"tags": [needsTagsStr, "asymmetric gameplay/victory", "board", "cards", "hidden information", themeStr + "supernatural horror"],
		"minPlayers": 2,
		"maxPlayers": 5,
		"numPlayersNote": [
			"",
			""
		],
		"minTime": 120,
		"maxTime": 180,
		"complexity": 0.00,
		"lastPlayed": noDataStr,
		"storageLocation": "Home",
		"description": "One player is Dracula, and is trying to fight off or evade the other players, who are hunters trying to track him down; Dracula moves in secret, laying clues and traps",
		"notes": "Has a quick-play option where some areas are inaccessible and the game starts partially in progress",
		"wip": false,
		"expansions": []
	},
	{
		"name": "Guildlands",
		"version": "",
		"url": "https://boardgamegeek.com/boardgame/447587/guildlands",
		"category": "Board Game",
		"gameplayType": "Competitive",
		"tags": ["asymmetric gameplay/victory", themeStr + "city building", "tile placement", "worker placement"],
		"minPlayers": 2,
		"maxPlayers": 6,
		"numPlayersNote": [
			"",
			""
		],
		"minTime": 45,
		"maxTime": 90,
		"complexity": 2.45,
		"lastPlayed": "2026",
		"storageLocation": "Car",
		"description": "Each player is a guild with their own abilities, and they have to place tiles to build a city and earn points based on their own win conditions",
		"notes": "Box signed by the game designer",
		"wip": false,
		"expansions": []
	},
	{
		"name": "Kalypso",
		"version": "",
		"url": "https://boardgamegeek.com/boardgame/446453/kalypso",
		"category": "Board Game",
		"gameplayType": "Competitive/Cooperative",
		"tags": [needsTagsStr, "board", themeStr + "city building", themeStr + "post-apocalypse", "tile placement"],
		"minPlayers": 1,
		"maxPlayers": 4,
		"numPlayersNote": [
			"",
			""
		],
		"minTime": 45,
		"maxTime": 60,
		"complexity": 2.5,
		"lastPlayed": noDataStr,
		"storageLocation": noDataStr,
		"description": "In a flooded post-apocalyptic world, collect salvage and construct a floating colony; has both cooperative and competitive modes",
		"notes": "",
		"wip": true,
		"expansions": []
	},
	{
		"name": "Lunar Rush",
		"version": "",
		"url": "https://boardgamegeek.com/boardgame/356873/lunar-rush",
		"category": "Board Game",
		"gameplayType": "Competitive",
		"tags": ["board", "cards", "no randomness", themeStr + "digging for resources", "worker placement"],
		"minPlayers": 1,
		"maxPlayers": 4,
		"numPlayersNote": [
			"Solo mode is basically just an optimization exercise",
			""
		],
		"minTime": 45,
		"maxTime": 75,
		"complexity": 2.85,
		"lastPlayed": "2025",
		"storageLocation": "Home",
		"description": "New minerals have been discovered on the moon, and everyone is a company with a moon base, in a race to mine and sell those minerals back on Earth",
		"notes": "",
		"wip": false,
		"expansions": []
	},
	{
		"name": "Nexus Infernum",
		"version": "",
		"url": "https://boardgamegeek.com/boardgame/257633/nexus-infernum",
		"category": "Board Game",
		"gameplayType": "Competitive",
		"tags": ["board", "dice", themeStr + "demons", "worker placement"],
		"minPlayers": 2,
		"maxPlayers": 5,
		"numPlayersNote": [
			"",
			""
		],
		"minTime": 45,
		"maxTime": 90,
		"complexity": 2,
		"lastPlayed": noDataStr,
		"storageLocation": "Home",
		"description": "Everyone is a necromancer trying to command skeletons, make pacts with fiends, and harness energy portals to dominate everything",
		"notes": "",
		"wip": false,
		"expansions": []
	},
	{
		"name": "Nuclear War",
		"version": "",
		"url": "https://boardgamegeek.com/boardgame/713/nuclear-war",
		"category": "Card Game",
		"gameplayType": "Competitive",
		"tags": ["cards", "last one standing", "player elimination", themeStr + "war"],
		"minPlayers": 2,
		"maxPlayers": 6,
		"numPlayersNote": [
			"",
			""
		],
		"minTime": 60,
		"maxTime": 60,
		"complexity": 1.44,
		"lastPlayed": "2010's",
		"storageLocation": "Home",
		"description": "Everyone is a nuclear world power, trying to be the last country standing; the game switches between \"cold war\", (where you fight with propaganda) and \"war\" (where you fight with, surprise, nukes) phases",
		"notes": "",
		"wip": false,
		"expansions": []
	},
	{
		"name": "Rebirth",
		"version": "",
		"url": "https://boardgamegeek.com/boardgame/417197/rebirth",
		"category": "Board Game",
		"gameplayType": "Competitive",
		"tags": [needsTagsStr, "board", themeStr + "post-apocalypse", "tile placement"],
		"minPlayers": 2,
		"maxPlayers": 4,
		"numPlayersNote": [
			"",
			""
		],
		"minTime": 45,
		"maxTime": 60,
		"complexity": 2,
		"lastPlayed": noDataStr,
		"storageLocation": "Home",
		"description": "In a post-apocalyptic world, everyone is a competing tribe trying to rebuild civilization first; the game has a simpler \"Scotland\" side and a more complex \"Ireland\" side",
		"notes": "",
		"wip": false,
		"expansions": []
	},
	{
		"name": "Red Tides: A Tale of New Caribbea",
		"version": "Deluxe Edition",
		"url": "https://boardgamegeek.com/boardgame/420575/red-tides-a-tale-of-new-caribbea",
		"category": "Board Game",
		"gameplayType": "Cooperative",
		"tags": [needsTagsStr, "board", themeStr + "pirates"],
		"minPlayers": 1,
		"maxPlayers": 4,
		"numPlayersNote": [
			"",
			""
		],
		"minTime": 60,
		"maxTime": 240,
		"complexity": 3,
		"lastPlayed": noDataStr,
		"storageLocation": noDataStr,
		"description": "Everyone is a pirate captain working together to try to stop the legendary pirate captain John Davies from taking over the whole Caribbean Sea",
		"notes": "",
		"wip": true,
		"expansions": []
	},
	{
		"name": "Restart",
		"version": "Deluxe Edition",
		"url": "https://boardgamegeek.com/boardgame/377045/restart",
		"category": "Board Game",
		"gameplayType": "Competitive",
		"tags": [needsTagsStr, "board", "cards", "dice", themeStr + "dystopia", themeStr + "time travel"],
		"minPlayers": 1,
		"maxPlayers": 4,
		"numPlayersNote": [
			"",
			""
		],
		"minTime": 60,
		"maxTime": 120,
		"complexity": 3.25,
		"lastPlayed": noDataStr,
		"storageLocation": noDataStr,
		"description": "After society becomes a dystopia, players compete to travel through time and ensure their preferred future comes to pass",
		"notes": "",
		"wip": true,
		"expansions": [
			{
				"name": "Duality Mini Expansion",
				"version": "Expansion",
				"url": "https://boardgamegeek.com/boardgameexpansion/469940/restart-duality-mini-expansion",
				"category": "Board Game",
				"gameplayType": "Competitive",
				"tags": [needsTagsStr, "board", "cards", "dice", themeStr + "dystopia", themeStr + "time travel"],
				"minPlayers": 1,
				"maxPlayers": 4,
				"numPlayersNote": [
					"",
					""
				],
				"minTime": 60,
				"maxTime": 120,
				"complexity": 0.00,
				"lastPlayed": noDataStr,
				"storageLocation": noDataStr,
				"description": "Two-colored cards can be used as either color, for greater flexibility",
				"notes": "",
				"wip": true
			},
			{
				"name": "Gadgets Expansion",
				"version": "Expansion",
				"url": "https://boardgamegeek.com/boardgameexpansion/469939/restart-gadgets-expansion",
				"category": "Board Game",
				"gameplayType": "Competitive",
				"tags": [needsTagsStr, "board", "cards", "dice", themeStr + "dystopia", themeStr + "time travel"],
				"minPlayers": 1,
				"maxPlayers": 4,
				"numPlayersNote": [
					"",
					""
				],
				"minTime": 60,
				"maxTime": 120,
				"complexity": 0.00,
				"lastPlayed": noDataStr,
				"storageLocation": noDataStr,
				"description": "Gadget cards for each type of dystopia add new abilities and options",
				"notes": "",
				"wip": true
			}
			/*
			,
			{
				"name": "Sand and Cables",
				"version": "Expansion",
				"url": "https://boardgamegeek.com/boardgameexpansion/428695/restart-sand-and-cables",
				"category": "Board Game",
				"gameplayType": "Competitive",
				"tags": [needsTagsStr, "board", "cards", "dice", themeStr + "dystopia", themeStr + "time travel"],
				"minPlayers": 1,
				"maxPlayers": 4,
				"numPlayersNote": [
					"",
					""
				],
				"minTime": 60,
				"maxTime": 120,
				"complexity": 0.00,
				"lastPlayed": noDataStr,
				"storageLocation": noDataStr,
				"description": "Two extra dystopian scenarios",
				"notes": "",
				"wip": true
			}
			*/
		]
	},
	{
		"name": "Risk",
		"version": "",
		"url": "https://boardgamegeek.com/boardgame/181/risk",
		"category": "Board Game",
		"gameplayType": "Competitive",
		"tags": ["board", "cards", "dice", "last one standing", "player elimination", themeStr + "war"],
		"minPlayers": 2,
		"maxPlayers": 6,
		"numPlayersNote": [
			"",
			""
		],
		"minTime": 120,
		"maxTime": 120,
		"complexity": 2.06,
		"lastPlayed": "2000's",
		"storageLocation": "Home",
		"description": "Deploy and move armies, then clash with other armies to take over the world",
		"notes": "Old game, some pieces may be missing",
		"wip": false,
		"expansions": []
	},
	{
		"name": "Root",
		"version": "",
		"url": "https://boardgamegeek.com/boardgame/237182/root",
		"category": "Board Game",
		"gameplayType": "Competitive",
		"tags": ["asymmetric gameplay/victory", "board", "cards", "dice", "worker placement"],
		"minPlayers": 2,
		"maxPlayers": 4,
		"numPlayersNote": [
			"",
			""
		],
		"minTime": 60,
		"maxTime": 90,
		"complexity": 3.83,
		"lastPlayed": "2020's",
		"storageLocation": "Home",
		"description": "Everyone plays a different faction of animals fighting an asymmetric war in the forest; each faction has different rules, resources, and victory conditions",
		"notes": "",
		"wip": false,
		"expansions": [
			{
				"name": "The Homeland Expansion",
				"version": "Expansion",
				"url": "https://boardgamegeek.com/boardgame/428335/root-the-homeland-expansion",
				"category": "Board Game",
				"gameplayType": "Competitive",
				"tags": ["asymmetric gameplay/victory", "board", "cards", "dice", "worker placement"],
				"minPlayers": 2,
				"maxPlayers": 6,
				"numPlayersNote": [
					"",
					"Expansion adds support for up to 6 players"
				],
				"minTime": 60,
				"maxTime": 90,
				"complexity": 3.91,
				"lastPlayed": noDataStr,
				"storageLocation": "Home",
				"description": "Adds new factions and mechanics to the base game, plus support for more players",
				"notes": "",
				"wip": false
			},
			{
				"name": "Homeland Hirelings Pack",
				"version": "Expansion",
				"url": "https://boardgamegeek.com/boardgameexpansion/431220/root-homeland-hirelings-pack",
				"category": "Board Game",
				"gameplayType": "Competitive",
				"tags": ["asymmetric gameplay/victory", "board", "cards", "dice", "worker placement"],
				"minPlayers": 2,
				"maxPlayers": 4,
				"numPlayersNote": [
					"",
					""
				],
				"minTime": 60,
				"maxTime": 90,
				"complexity": 3.33,
				"lastPlayed": noDataStr,
				"storageLocation": "Home",
				"description": "Adds three new hirelings available to any player",
				"notes": "",
				"wip": false
			},
			{
				"name": "The Squires and Disciples Deck",
				"version": "Expansion",
				"url": "https://boardgamegeek.com/boardgameexpansion/431218/root-the-squires-and-disciples-deck",
				"category": "Board Game",
				"gameplayType": "Competitive",
				"tags": ["asymmetric gameplay/victory", "board", "cards", "dice", "worker placement"],
				"minPlayers": 2,
				"maxPlayers": 4,
				"numPlayersNote": [
					"",
					""
				],
				"minTime": 60,
				"maxTime": 90,
				"complexity": 3.20,
				"lastPlayed": noDataStr,
				"storageLocation": "Home",
				"description": "An alternative deck to use that supports content from Homeland",
				"notes": "",
				"wip": false
			}
		]
	},
	{
		"name": "Secret Hitler",
		"version": "",
		"url": "https://boardgamegeek.com/boardgame/188834/secret-hitler",
		"category": "Board Game",
		"gameplayType": "Team-Competitive",
		"tags": ["board", "cards", "hidden information", "player elimination", "traitor(s)"],
		"minPlayers": 5,
		"maxPlayers": 10,
		"numPlayersNote": [
			"",
			""
		],
		"minTime": 45,
		"maxTime": 45,
		"complexity": 1.74,
		"lastPlayed": "2026",
		"storageLocation": "Home",
		"description": "Social deduction game where a minority of player are Fascists, trying to get Hitler into power without being identified by the rest",
		"notes": "",
		"wip": false,
		"expansions": []
	},
	{
		"name": "Spirit Island",
		"version": "",
		"url": "https://boardgamegeek.com/boardgame/162886/spirit-island",
		"category": "Board Game",
		"gameplayType": "Cooperative",
		"tags": [needsTagsStr, "area defense", "board", "cards"],
		"minPlayers": 1,
		"maxPlayers": 4,
		"numPlayersNote": [
			"",
			""
		],
		"minTime": 90,
		"maxTime": 120,
		"complexity": 4.08,
		"lastPlayed": "2020's",
		"storageLocation": "Home",
		"description": "Each player is a different guardian spirit of a primitive island being invaded by colonizers; the spirits must protect the natives and repel the invaders",
		"notes": "",
		"wip": false,
		"expansions": [
			{
				"name": "Jagged Earth",
				"version": "Expansion",
				"url": "https://boardgamegeek.com/boardgame/262722/spirit-island-jagged-earth",
				"category": "Board Game",
				"gameplayType": "Cooperative",
				"tags": [needsTagsStr, "area defense", "board", "cards"],
				"minPlayers": 1,
				"maxPlayers": 6,
				"numPlayersNote": [
					"",
					"Expansion adds support for up to 6 players"
				],
				"minTime": 90,
				"maxTime": 120,
				"complexity": 4.52,
				"lastPlayed": noDataStr,
				"storageLocation": "Home",
				"description": "Adds more spirits, new maps, support for more players, new game modes, and more to the base game",
				"notes": "",
				"wip": false
			}
		]
	},
	{
		"name": "Super Pixel Tactics",
		"version": "",
		"url": "https://boardgamegeek.com/boardgame/442750/super-pixel-tactics",
		"category": "Card Game",
		"gameplayType": "Competitive",
		"tags": [needsTagsStr, "cards"],
		"minPlayers": 2,
		"maxPlayers": 2,
		"numPlayersNote": [
			"",
			""
		],
		"minTime": 30,
		"maxTime": 30,
		"complexity": 0,
		"lastPlayed": noDataStr,
		"storageLocation": noDataStr,
		"description": "Two players duel with heroes",
		"notes": "",
		"wip": true,
		"expansions": []
	},
	{
		"name": "Tacta",
		"version": "",
		"url": "https://boardgamegeek.com/boardgame/401636/tacta",
		"category": "Card Game",
		"gameplayType": "Competitive",
		"tags": [needsTagsStr, "cards"],
		"minPlayers": 2,
		"maxPlayers": 6,
		"numPlayersNote": [
			"",
			""
		],
		"minTime": 20,
		"maxTime": 20,
		"complexity": 1.45,
		"lastPlayed": "2026",
		"storageLocation": "Car",
		"description": "Each player has a different card color, with different numbers of dots and geometric shapes; you place your cards on top of your opponents' cards by aligning with their geometry, trying to cover up their dots and reveal your own",
		"notes": "",
		"wip": false,
		"expansions": []
	},
	{
		"name": "Terraria: The Board Game",
		"version": "",
		"url": "https://boardgamegeek.com/boardgame/391286/terraria-the-board-game",
		"category": "Board Game",
		"gameplayType": "Cooperative",
		"tags": ["board", "cards", "dice", themeStr + "digging for resources"],
		"minPlayers": 1,
		"maxPlayers": 4,
		"numPlayersNote": [
			"",
			""
		],
		"minTime": 120,
		"maxTime": 180,
		"complexity": 3,
		"lastPlayed": noDataStr,
		"storageLocation": "Home",
		"description": "Players work together to explore the world, collect resources, defeat bosses, and eventually conquer the Wall of Flesh",
		"notes": "Based on the 2D multiplayer game Terraria",
		"wip": false,
		"expansions": []
	},
	{
		"name": "The Flames of Fafnir",
		"version": "",
		"url": "https://boardgamegeek.com/boardgame/402278/the-flames-of-fafnir",
		"category": "Board Game",
		"gameplayType": "Competitive/Cooperative",
		"tags": [needsTagsStr, "area defense", "board"],
		"minPlayers": 1,
		"maxPlayers": 4,
		"numPlayersNote": [
			"",
			""
		],
		"minTime": 90,
		"maxTime": 120,
		"complexity": 2,
		"lastPlayed": noDataStr,
		"storageLocation": noDataStr,
		"description": "Players work together to place barricades to protect a village from the dragon Fafnir, using IRL physics for the fireballs and the barricades; after Fafnir is defeated, players compete to be the village hero",
		"notes": "",
		"wip": true,
		"expansions": []
	},
	{
		"name": "The Night Cage",
		"version": "",
		"url": "https://boardgamegeek.com/boardgame/306709/the-night-cage",
		"category": "Board Game",
		"gameplayType": "Cooperative",
		"tags": [needsTagsStr, themeStr + "supernatural horror", "tile placement"],
		"minPlayers": 1,
		"maxPlayers": 5,
		"numPlayersNote": [
			"",
			""
		],
		"minTime": 40,
		"maxTime": 60,
		"complexity": 2.14,
		"lastPlayed": noDataStr,
		"storageLocation": "Home",
		"description": "Everyone is trapped and trying to escape from a dark maze that reshuffles when you lose line of sight; your light source has limited duration, and if everyone runs out of light, you all lose",
		"notes": "Has <a href=\"https://music.youtube.com/playlist?list=OLAK5uy_lqwoW6p5cgFeO_tHOb7LsWhRZXWyVR7lA\">its own musical score</a> composed and arranged by the devs",
		"wip": false,
		"expansions": []
	},
	{
		"name": "The Old King's Crown",
		"version": "",
		"url": "https://boardgamegeek.com/boardgame/357873/the-old-kings-crown",
		"category": "Board Game",
		"gameplayType": "Competitive",
		"tags": [needsTagsStr, "board", "cards", themeStr + "competing for the crown"],
		"minPlayers": 1,
		"maxPlayers": 4,
		"numPlayersNote": [
			"",
			""
		],
		"minTime": 60,
		"maxTime": 120,
		"complexity": 3.65,
		"lastPlayed": noDataStr,
		"storageLocation": "Home",
		"description": "Players compete for the crown using different tactics based on cards drawn, across multiple phases",
		"notes": "",
		"wip": false,
		"expansions": []
	},
	{
		"name": "Ultimate Werewolf",
		"version": "",
		"url": "https://boardgamegeek.com/boardgame/152241/ultimate-werewolf",
		"category": "Card Game",
		"gameplayType": "Team-Competitive",
		"tags": ["cards", "hidden information", "player elimination", "traitor(s)"],
		"minPlayers": 5,
		"maxPlayers": 30,
		"numPlayersNote": [
			"",
			""
		],
		"minTime": 30,
		"maxTime": 90,
		"complexity": 1.15,
		"lastPlayed": "2010's",
		"storageLocation": "Car",
		"description": "Classic social deduction. Everyone has a role, the townspeople want to find and exile the werewolves and the werewolves want to eat all the townies",
		"notes": "",
		"wip": false,
		"expansions": []
	},
	{
		"name": "Unearth",
		"version": "Complete Edition",
		"url": "https://boardgamegeek.com/boardgame/466688/unearth-10th-anniversary-edition",
		"category": "Board Game",
		"gameplayType": "Competitive",
		"tags": [needsTagsStr, "board", themeStr + "digging for resources"],
		"minPlayers": 1,
		"maxPlayers": 5,
		"numPlayersNote": [
			"Complete edition includes expansion for solo play",
			"Base game is 2-4, complete edition includes expansion for 5 players"
		],
		"minTime": 30,
		"maxTime": 60,
		"complexity": 1.93,
		"lastPlayed": noDataStr,
		"storageLocation": noDataStr,
		"description": "Everyone is an explorer delving into ancient ruins, trying to claim them; can either win with high rolls to claim Ruins, or with low rolls to create Wonders",
		"notes": "",
		"wip": true,
		"expansions": []
	},
	{
		"name": "Worms: The Board Game",
		"version": "",
		"url": "https://boardgamegeek.com/boardgame/397788/worms-the-board-game",
		"category": "Board Game",
		"gameplayType": "Competitive",
		"tags": ["cards", "dice", "last one standing", "player elimination", "tile placement"],
		"minPlayers": 2,
		"maxPlayers": 6,
		"numPlayersNote": [
			"",
			""
		],
		"minTime": 45,
		"maxTime": 45,
		"complexity": 2.1,
		"lastPlayed": noDataStr,
		"storageLocation": "Home",
		"description": "Squads of worms compete to blow each other up on a destructible battlefield made of random hex tiles",
		"notes": "Based on the video game franchise Worms",
		"wip": false,
		"expansions": []
	}
	/*
	,
	{
		"name": "",
		"version": "",
		"url": "",
		"category": "",
		"gameplayType": "",
		"tags": [],
		"minPlayers": 0,
		"maxPlayers": 0,
		"numPlayersNote": [
			"",		// for min players
			""		// for max players
		],
		"minTime": 0,
		"maxTime": 0,
		"complexity": 0.00,
		"lastPlayed": noDataStr,
		"storageLocation": noDataStr,
		"description": "",
		"notes": "",
		"wip": false,
		"expansions": [
			{
				"name": "",
				"version": "",
				"url": "",
				"category": "",
				"gameplayType": "",
				"tags": [],
				"minPlayers": 0,
				"maxPlayers": 0,
				"numPlayersNote": [
					"",
					""
				],
				"minTime": 0,
				"maxTime": 0,
				"complexity": 0.00,
				"lastPlayed": noDataStr,
				"storageLocation": noDataStr,
				"description": "",
				"notes": "",
				"wip": false
			}
		]
	}
	*/
],
undecidedPurchases = [
	{
		name: "Nemesis",
		url: "https://boardgamegeek.com/boardgame/167355/nemesis",
		description: "Kind of like The Thing, trying to survive aliens hunting them while there is a traitor",
		price: "$125-140",
		players: "?",
		gameplayType: "Competitive/Cooperative",
		officialWebsite: "https://awakenrealms.com/games/awaken-realms/nemesis"
	},
	{
		name: "Underwater Cities",
		url: "https://boardgamegeek.com/boardgame/247763/underwater-cities",
		description: "Place cards to basically build Rapture from Bioshock, trying to be the best underwater architect",
		price: "$49-65",
		players: "?",
		gameplayType: "Competitive",
		officialWebsite: "https://deliciousgames.org/underwater-cities"
	},
	{
		name: "Avalon Big Box",
		url: "https://boardgamegeek.com/boardgame/367396/avalon-big-box",
		description: "Social deduction game with King Arthur/Camelot flavor",
		price: "$40",
		players: "?",
		gameplayType: "Team-Competitive",
		officialWebsite: "https://indieboardsandcards.com/our-games/avalon-big-box/"
	},
	{
		name: "Fantastic Factories",
		url: "https://boardgamegeek.com/boardgame/216600/fantastic-factories",
		description: "Make factories, allocate resources, and place workers to manufacture the most goods",
		price: "$30-50",
		players: "?",
		gameplayType: "Competitive",
		officialWebsite: "https://friendlyskeleton.com/products/fantastic-factories-1"
	},
	{
		name: "Sub Terra",
		url: "https://boardgamegeek.com/boardgame/204472/sub-terra",
		description: "Procedurally generated co-op cave survival with DRG-like roles, limited light like Night Cage",
		price: "$180",
		players: "?",
		gameplayType: "Cooperative",
		officialWebsite: "https://naylorgames.com/collections/sub-terra"
	},
	{
		name: "Unsettled",
		url: "https://boardgamegeek.com/boardgame/290484/unsettled",
		description: "Co-op survival on unexplored planets, no hostile encounters, just trying to keep systems running and survive the environment",
		price: "$99-400",
		players: "?",
		gameplayType: "Cooperative",
		officialWebsite: "https://orangenebula.com/collections/unsettled"
	},
	{
		name: "Beyond the Sun",
		url: "https://boardgamegeek.com/boardgame/317985/beyond-the-sun",
		description: "Explore and expand through the galaxy, develop through economy, science, and politics",
		price: "$60-70",
		players: "?",
		gameplayType: "Competitive",
		officialWebsite: "https://www.riograndegames.com/games/beyond-the-sun/"
	},
	{
		name: "Blood on the Clocktower",
		url: "https://boardgamegeek.com/boardgame/240980/blood-on-the-clocktower",
		description: "Social deduction, a demon and his minions committing murders at night while townsfolk try to execute the demon during the day",
		price: "$135-170",
		players: "?",
		gameplayType: "Team-Competitive",
		officialWebsite: "https://bloodontheclocktower.com/"
	},
	{
		name: "Inis",
		url: "https://boardgamegeek.com/boardgame/155821/inis",
		description: "Competing to become king of the island, different victory conditions that you can strive for",
		price: "$60-70",
		players: "?",
		gameplayType: "Competitive",
		officialWebsite: "https://www.matagot.com/en/catalog/details/expert-games/1/inis/794"
	},
	{
		name: "Vast: The Crystal Caverns",
		url: "https://boardgamegeek.com/boardgame/170416/vast-the-crystal-caverns",
		description: "<b>(OUT OF PRINT)</b> Players take different asymmetric roles like Knight, Dragon, Goblins, and the Cave itself",
		price: "$75",
		players: "?",
		gameplayType: "Competitive",
		officialWebsite: "https://ledergames.com/products/vast-the-crystal-caverns"
	},
	{
		name: "Everdell",
		url: "https://boardgamegeek.com/boardgame/199792/everdell",
		description: "Woodland animals compete to build new cities in the forest with workers and resources, best city wins",
		price: "$40-80",
		players: "1-4",
		gameplayType: "Competitive",
		officialWebsite: "https://www.tabletoptycoon.com/products/everdell-standard-edition-3rd-edition"
	},
	{
		name: "Deep Rock Galactic: The Board Game",
		url: "https://boardgamegeek.com/boardgame/348220/deep-rock-galactic-the-board-game",
		description: "ROCK AND STONE",
		price: "$156",
		players: "1-4",
		gameplayType: "Cooperative",
		officialWebsite: "https://moodpublishing.com/products/deep-rock-galactic-base-game-deluxe-2nd-edition"
	}
	/*
	,
	{
		name: "",
		url: "",
		description: "",
		price: "",
		players: "",
		gameplayType: "",
		officialWebsite: ""
	}
	*/
];